apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /data/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          target_label: app
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_container_name]
          separator: /
          regex: (.+);(.+)
          replacement: /var/log/pods/$1/$2/*.log
          target_label: __path__
      pipeline_stages:
        - json:
            expressions:
              level: level
              timestamp: timestamp
              message: message
              correlation_id: correlation_id
              component: component
        - labels:
            level:
            correlation_id:
            component:
