apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-server
  namespace: video-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-server
  template:
    metadata:
      labels:
        app: video-server
    spec:
      containers:
      - name: video-server
        image: video-server:latest
        # Add this to your container spec in deployment.yaml
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: video-config
              key: minio-endpoint
        - name: MINIO_BUCKET
          valueFrom:
            configMapKeyRef:
              name: video-config
              key: minio-bucket
        - name: MINIO_USE_SSL
          valueFrom:
            configMapKeyRef:
              name: video-config
              key: minio-use-ssl
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: secret-key
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: video-config
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: video-config
              key: db-name
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: video-config
              key: log-level
              optional: true
        resources:
          requests:
            memory: "100Mi"
            cpu: "1m"
          limits:
            memory: "200Mi"
            cpu: "2m"
