apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: video-app
type: Opaque
data:
  # Base64 encoded values
  user: cG9zdGdyZXM=      # "postgres"
  password: cGFzc3dvcmQ=  # "password"